# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
 
language: objective-c
osx_image: xcode7.2
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- cd GRKAnalyticsLib; pod install; cd ..
script:
- set -o pipefail && xcodebuild test -project GRKAnalyticsLib/GRKAnalyticsLib.xcodeproj -scheme ios -destination "platform=iOS Simulator,OS=9.2,name=iPhone 6" ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
